import datetime


def generate_headers(routing_model):



    current_year = datetime.datetime.now().year

    f = open("./p4src/common/headers.p4", "w")

    # License
    f.write("/*******************************************************************************\n")
    f.write(" * Copyright " + str(current_year) + " INTRIG\n")
    f.write(" *\n")
    f.write(" * Licensed under the Apache License, Version 2.0 (the \"License\");\n")
    f.write(" * you may not use this file except in compliance with the License.\n")
    f.write(" * You may obtain a copy of the License at\n")
    f.write(" *\n")
    f.write(" *     http://www.apache.org/licenses/LICENSE-2.0\n")
    f.write(" *\n")
    f.write(" * Unless required by applicable law or agreed to in writing, software\n")
    f.write(" * distributed under the License is distributed on an \"AS IS\" BASIS,\n")
    f.write(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n")
    f.write(" * See the License for the specific language governing permissions and\n")
    f.write(" * limitations under the License.\n")
    f.write(" ******************************************************************************/\n")
    f.write("\n")


    #headers
    f.write("#ifndef _HEADERS_\n")
    f.write("#define _HEADERS_\n")
    f.write("\n")
    f.write("typedef bit<48> mac_addr_t;\n")
    f.write("typedef bit<32> ipv4_addr_t;\n")
    f.write("typedef bit<128> ipv6_addr_t;\n")
    f.write("typedef bit<12> vlan_id_t;\n\n")

    f.write("typedef bit<16> ether_type_t;\n")
    f.write("const ether_type_t ETHERTYPE_IPV4 = 16w0x0800;\n")
    f.write("const ether_type_t ETHERTYPE_REC = 16w0x9966;\n")
    f.write("const ether_type_t ETHERTYPE_ARP = 16w0x0806;\n")
    f.write("const ether_type_t ETHERTYPE_IPV6 = 16w0x86dd;\n")
    f.write("const ether_type_t ETHERTYPE_VLAN = 16w0x8100;\n\n")

    f.write("typedef bit<8> ip_protocol_t;\n")
    f.write("const ip_protocol_t IP_PROTOCOLS_ICMP = 1;\n")
    f.write("const ip_protocol_t IP_PROTOCOLS_TCP = 6;\n")
    f.write("const ip_protocol_t IP_PROTOCOLS_UDP = 17;\n\n")

    f.write("header ethernet_h {\n")
    f.write("    mac_addr_t dst_addr;\n")
    f.write("    mac_addr_t src_addr;\n")
    f.write("    bit<16> ether_type;\n")
    f.write("}\n\n")
    
    if routing_model == 2:
        f.write("//optimized for user routing\n")
        f.write("header rec_h {\n")
        f.write("    bit<32> ts;\n")
        f.write("    bit<16> sw;\n")
        f.write("    bit<16> sw_id;\n")
        f.write("    bit<16> ether_type;\n")
        f.write("}\n\n")
    else:
        f.write("//original\n")
        f.write("header rec_h {\n")
        f.write("    bit<32> ts;\n")
        f.write("    bit<32> num;\n")
        f.write("    bit<32> jitter;\n")
        f.write("    bit<16> sw;\n")
        f.write("    bit<16> sw_id;\n")
        f.write("    bit<16> ether_type;\n")
        f.write("    bit<32> dest_ip;\n")
        f.write("    bit<1> signal;\n")
        f.write("    bit<31> pad;\n")
        f.write("    bit<160> routeid;\n")
        f.write("}\n\n")


    f.write("header vlan_tag_h {\n")
    f.write("    bit<3> pcp;\n")
    f.write("    bit<1> cfi;\n")
    f.write("    vlan_id_t vid;\n")
    f.write("    bit<16> ether_type;\n")
    f.write("}\n\n")

    f.write("header mpls_h {\n")
    f.write("    bit<20> label;\n")
    f.write("    bit<3> exp;\n")
    f.write("    bit<1> bos;\n")
    f.write("    bit<8> ttl;\n")
    f.write("}\n\n")

    f.write("header ipv4_h {\n")
    f.write("    bit<4> version;\n")
    f.write("    bit<4> ihl;\n")
    f.write("    bit<8> diffserv;\n")
    f.write("    bit<16> total_len;\n")
    f.write("    bit<16> identification;\n")
    f.write("    bit<16> flags;\n")
    f.write("    bit<8> ttl;\n")
    f.write("    bit<8> protocol;\n")
    f.write("    bit<16> hdr_checksum;\n")
    f.write("    ipv4_addr_t src_addr;\n")
    f.write("    ipv4_addr_t dst_addr;\n")
    f.write("}\n\n")

    f.write("header ipv6_h {\n")
    f.write("    bit<4> version;\n")
    f.write("    bit<8> traffic_class;\n")
    f.write("    bit<20> flow_label;\n")
    f.write("    bit<16> payload_len;\n")
    f.write("    bit<8> next_hdr;\n")
    f.write("    bit<8> hop_limit;\n")
    f.write("    ipv6_addr_t src_addr;\n")
    f.write("    ipv6_addr_t dst_addr;\n")
    f.write("}\n\n")

    f.write("header tcp_h {\n")
    f.write("    bit<16> src_port;\n")
    f.write("    bit<16> dst_port;\n")
    f.write("    bit<32> seq_no;\n")
    f.write("    bit<32> ack_no;\n")
    f.write("    bit<4> data_offset;\n")
    f.write("    bit<4> res;\n")
    f.write("    bit<8> flags;\n")
    f.write("    bit<16> window;\n")
    f.write("    bit<16> checksum;\n")
    f.write("    bit<16> urgent_ptr;\n")
    f.write("}\n\n")

    f.write("header udp_h {\n")
    f.write("    bit<16> src_port;\n")
    f.write("    bit<16> dst_port;\n")
    f.write("    bit<16> hdr_length;\n")
    f.write("    bit<16> checksum;\n")
    f.write("}\n\n")

    f.write("header icmp_h {\n")
    f.write("    bit<8> type_;\n")
    f.write("    bit<8> code;\n")
    f.write("    bit<16> hdr_checksum;\n")
    f.write("}\n\n")


    f.write("// Address Resolution Protocol -- RFC 6747\n")
    f.write("header arp_h {\n")
    f.write("    bit<16> hw_type;\n")
    f.write("    bit<16> proto_type;\n")
    f.write("    bit<8> hw_addr_len;\n")
    f.write("    bit<8> proto_addr_len;\n")
    f.write("    bit<16> opcode;\n")
    f.write("    bit<48> hwSrcAddr;\n")
    f.write("    bit<32> protoSrcAddr;\n")
    f.write("    bit<48> hwDstAddr;\n")
    f.write("    bit<32> dest_ip;\n")
    f.write("}\n\n")

    f.write("// Segment Routing Extension (SRH) -- IETFv7\n")
    f.write("header ipv6_srh_h {\n")
    f.write("    bit<8> next_hdr;\n")
    f.write("    bit<8> hdr_ext_len;\n")
    f.write("    bit<8> routing_type;\n")
    f.write("    bit<8> seg_left;\n")
    f.write("    bit<8> last_entry;\n")
    f.write("    bit<8> flags;\n")
    f.write("    bit<16> tag;\n")
    f.write("}\n\n")

    f.write("// VXLAN -- RFC 7348\n")
    f.write("header vxlan_h {\n")
    f.write("    bit<8> flags;\n")
    f.write("    bit<24> reserved;\n")
    f.write("    bit<24> vni;\n")
    f.write("    bit<8> reserved2;\n")
    f.write("}\n\n")

    f.write("// Generic Routing Encapsulation (GRE) -- RFC 1701\n")
    f.write("header gre_h {\n")
    f.write("    bit<1> C;\n")
    f.write("    bit<1> R;\n")
    f.write("    bit<1> K;\n")
    f.write("    bit<1> S;\n")
    f.write("    bit<1> s;\n")
    f.write("    bit<3> recurse;\n")
    f.write("    bit<5> flags;\n")
    f.write("    bit<3> version;\n")
    f.write("    bit<16> proto;\n")
    f.write("}\n\n")


    f.write("struct header_t {\n")
    f.write("    ethernet_h ethernet;\n")
    f.write("    vlan_tag_h vlan_tag;\n")
    f.write("    ipv4_h ipv4;\n")
    f.write("    ipv6_h ipv6;\n")
    f.write("    tcp_h tcp;\n")
    f.write("    udp_h udp;\n")
    f.write("    rec_h rec;\n")
    f.write("}\n\n")


    f.write("struct headers {\n")
    f.write("    ethernet_h   ethernet;\n")
    f.write("    rec_h        rec;\n")
    f.write("    vlan_tag_h   vlan_tag;\n")
    f.write("    arp_h       arp;\n")
    f.write("    ipv4_h       ipv4;\n")
    f.write("    tcp_h       tcp;\n")
    f.write("    udp_h       udp;\n")
    f.write("}\n\n")

    f.write("struct empty_header_t {\n")
    f.write("}\n")

    f.write("struct empty_metadata_t {\n")
    f.write("}\n\n")

    f.write("#endif /* _HEADERS_ */\n")

    f.close()
